-- Crear la BBDD
CREATE DATABASE IF NOT EXISTS compania_aerea;

-- Para operar con la BBDD
USE compania_aerea;


-- T_PASAJERO
CREATE TABLE IF NOT EXISTS T_PASAJERO(
  DNI CHAR(9) PRIMARY KEY NOT NULL,
  Nombre VARCHAR(50) NOT NULL,
  Apellidos VARCHAR (100) NOT NULL,
  Email VARCHAR (100) NOT NULL
);

-- T_TELEFONO_PASAJERO
CREATE TABLE IF NOT EXISTS T_TELEFONO_PASAJERO(
  DNI_Pasajero CHAR(9) NOT NULL,
  Telefono TINYINT NOT NULL,
  PRIMARY KEY(DNI_Pasajero, Telefono),
  CONSTRAINT FK_PASAJERO_TELEFONO
    FOREIGN KEY (DNI_Pasajero) REFERENCES T_PASAJERO(DNI)
);

-- T_AVION
CREATE TABLE IF NOT EXISTS T_AVION(
  Matricula TINYINT PRIMARY KEY NOT NULL,
  Fabricante VARCHAR (50) NOT NULL,
  Modelo VARCHAR (50) NOT NULL,
  Capacidad TINYINT NOT NULL,
  Autonomia INT NOT NULL
);

-- T_VUELO
CREATE TABLE IF NOT EXISTS T_VUELO(
  Id_Vuelo INT(9) PRIMARY KEY NOT NULL,
  Matricula_Avion TINYINT NOT NULL,
  Origen VARCHAR (50) NOT NULL,
  Destino VARCHAR (50) NOT NULL,
  Fecha DATE NOT NULL,
  CONSTRAINT FK_VUELO_AVION
    FOREIGN KEY (Matricula_Avion) REFERENCES T_AVION(Matricula)
);

-- T_DISTRIBUCION
CREATE TABLE IF NOT EXISTS T_DISTRIBUCION(
  DNI_Pasajero CHAR(9) NOT NULL,
  Id_Vuelo INT(9) NOT NULL,
  Asiento CHAR(6) NOT NULL,
  Clase VARCHAR(50) NOT NULL,
  PRIMARY KEY(DNI_Pasajero, Id_Vuelo),
  CONSTRAINT FK_DISTRIBUCION_PASAJERO
    FOREIGN KEY (DNI_Pasajero) REFERENCES T_PASAJERO(DNI),
  CONSTRAINT FK_DISTRIBUCION_VUELO
    FOREIGN KEY (Id_Vuelo) REFERENCES T_VUELO(Id_Vuelo)
);

-- T_CAT_PROFESIONAL
CREATE TABLE IF NOT EXISTS T_CAT_PROFESIONAL(
  Cod_Categoria CHAR(9) PRIMARY KEY NOT NULL,
  Nombre VARCHAR(50) NOT NULL
);

-- T_PERSONAL
CREATE TABLE IF NOT EXISTS T_PERSONAL(
  Id_Trabajador INT(9) PRIMARY KEY NOT NULL,
  Cod_Categoria CHAR(9) NOT NULL,
  Nombre VARCHAR(50) NOT NULL,
  Apellido1 VARCHAR(100) NOT NULL,
  Apellido2 VARCHAR(100) NULL,
  CONSTRAINT FK_PERSONAL_CATEGORIA
    FOREIGN KEY (Cod_Categoria) REFERENCES T_CAT_PROFESIONAL(Cod_Categoria)
);

-- T_PUESTO
CREATE TABLE IF NOT EXISTS T_PUESTO(
  Id_Trabajador INT(9) NOT NULL,
  Id_Vuelo INT(9) NOT NULL,
  Puesto VARCHAR(50) NOT NULL,
  CONSTRAINT FK_PUESTO_PERSONAL
    FOREIGN KEY (Id_Trabajador) REFERENCES T_PERSONAL(Id_Trabajador),
  CONSTRAINT FK_PUESTO_VUELO
    FOREIGN KEY (Id_Vuelo) REFERENCES T_VUELO(Id_Vuelo)
);

-- T_TELEFONO_PERSONAL
CREATE TABLE IF NOT EXISTS T_TELEFONO_PERSONAL(
  Id_Trabajador INT(9) NOT NULL,
  Telefono TINYINT NOT NULL,
  PRIMARY KEY(Id_Trabajador, Telefono),
  CONSTRAINT FK_TELEFONO_TRABAJADOR
    FOREIGN KEY (Id_Trabajador) REFERENCES T_PERSONAL(Id_Trabajador)
);
